extends:
  - react-app

parserOptions:
  project: ./tsconfig.app.json

overrides:
  - files:
      - vite.config.ts
    parserOptions:
      project: ./tsconfig.node.json

rules:
  no-restricted-syntax:
    - error
    - selector: "[object.type=MetaProperty][property.name=env]"
      message: Use instead import { env } from "lib/env"
