version: "3.9"

services:
  app:
    platform: linux/amd64
    build:
      context: .
      args:
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
        SOURCE_VERSION: ${SOURCE_VERSION}
    image: ideanick-image
    container_name: ideanick-container
    env_file:
      - ./frontend/.env
      - ./backend/.env
      - ./.env.docker
    ports:
      - "${PORT}:${PORT}"
